version: "3"
services:
    mongo:
        image: ${MONGO_IMAGE}
        container_name: smalr-mongo
        restart: always
        environment:
            MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
        command: mongod --port 27018
        ports:
            - ${MONGO_PORT}:${MONGO_PORT}
    web:
        container_name: smalr-web
        build:
            context: .
            dockerfile: Dockerfile
        entrypoint:
            - flask
            - run
            - --host=${HOST}
        environment:
          PYTHONUNBUFFERED: 1
          FLASK_DEBUG: 1
        ports:
            - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
        depends_on:
            - mongo
        links:
            - mongo
        volumes: [".:/app"]